const LISTISSUE = {
  LOADING: 'LISTISSUE_LOADING',
  FETCH_SUCCESS: 'LISTISSUE_FETCH_SUCCESS',
  FETCH_FAILED: 'LISTISSUE_FETCH_FAILED',
  FETCH_REPO_SUCCESS: 'LISTISSUE_FETCH_SUCCESS_REPO',
  FETCH_REPO_FAILED: 'LISTISSUE_FETCH_FAILED_REPO'
};

const ISSUEDETAIL = {
  LOADING: 'ISSUEDETAIL_LOADING',
  FETCH_DETAIL_SUCCESS: 'ISSUEDETAIL_FETCH_DETAIL_SUCCESS',
  FETCH_DETAIL_FAILED: 'ISSUEDETAIL_FETCH_DETAIL_SUCCESS',
}


export { LISTISSUE, ISSUEDETAIL };
